## Array Manipulation.

In [3]:
import numpy as np

In [3]:
arr = np.random.randint(1,10 , (3,4))
arr

## reshape()

In [5]:
arr.reshape(6,2)

array([[4, 4],
       [8, 6],
       [8, 2],
       [5, 8],
       [5, 2],
       [8, 9]])

In [6]:
arr.reshape(2,6)

array([[4, 4, 8, 6, 8, 2],
       [5, 8, 5, 2, 8, 9]])

In [8]:
arr.reshape(2,-242342)

array([[4, 4, 8, 6, 8, 2],
       [5, 8, 5, 2, 8, 9]])

## Transpose

In [10]:
arr.T
arr

array([[4, 8, 5],
       [4, 2, 2],
       [8, 5, 8],
       [6, 8, 9]])

## flatten()

The flatten() function in NumPy is used to convert a multi-dimensional array into a one-dimensional array. This is useful for various purposes, such as simplifying data manipulation or preparing data for algorithms that require a flat input.

Key Points about flatten()
Returns a New Array: flatten() returns a new array that is a copy of the original array, flattened into one dimension.
Original Array Remains Unchanged: The original array is not modified by flatten().

In [12]:
arr.flatten()

array([4, 4, 8, 6, 8, 2, 5, 8, 5, 2, 8, 9])

## expand_dims()

The numpy.expand_dims() function is used to add a new axis (or dimension) to an array, effectively increasing its dimensionality. This can be useful for various operations where you need to adjust the shape of an array to be compatible with certain functions or broadcasting rules.

Key Points
Inserts New Axes: The axis parameter specifies the position where the new axis will be inserted. If the array has shape (2, 3), and you use axis=0, the result will have shape (1, 2, 3).
Array Shape Changes: The new dimension will be of size 1, which means it adds an additional axis without altering the data of the array.

Compatible with Broadcasting: Expanding dimensions can help align array shapes for broadcasting and other operations.

In [1]:
arr1 = np.array([1,2,3,3,4])
arr1.ndim

NameError: name 'np' is not defined

In [16]:
np.expand_dims(arr1 ,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [17]:
np.expand_dims(arr1 ,axis=0)

array([[1, 2, 3, 3, 4]])

In [18]:
arr

array([[4, 4, 8, 6],
       [8, 2, 5, 8],
       [5, 2, 8, 9]])

## squeeze()

The numpy.squeeze() function is used to remove single-dimensional entries from the shape of an array. This function is useful when you want to reduce the dimensionality of an array by removing axes that have a size of 1.

Key Points:

Remove Single-Dimensional Axes: By default, squeeze() removes all axes with a size of 1.

Specify Axes: If you want to remove specific axes, you can provide them in the axis parameter as a tuple or a single integer.

Shape Changes: The resulting array has the same data but with reduced dimensionality.

** Overall, squeeze() is a handy function for reducing the dimensionality of arrays and simplifying array shapes in NumPy.

In [19]:
np.squeeze(arr)

array([[4, 4, 8, 6],
       [8, 2, 5, 8],
       [5, 2, 8, 9]])

In [21]:
data = np.array([[1] , [2] , [3]])
data

In [23]:
np.squeeze(data)

array([1, 2, 3])

####  Example 1: Removing All Single-Dimensional Axes


In [4]:
# Create an array with shape (1, 2, 1, 3)
array = np.array([[[[1, 2, 3]], [[4, 5, 6]]]])

# Remove all single-dimensional axes
squeezed_array = np.squeeze(array)

print(squeezed_array)
print(squeezed_array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


#### Example 2: Removing Specific Axes

In [5]:
# Create an array with shape (1, 2, 1, 3)
array = np.array([[[[1, 2, 3]], [[4, 5, 6]]]])

# Remove specific single-dimensional axis
squeezed_array = np.squeeze(array, axis=0)

print(squeezed_array)
print(squeezed_array.shape)

[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


#### Example 3: Trying to Remove Non-Single-Dimensional Axes

In [6]:
# Create an array with shape (1, 2, 1, 3)
array = np.array([[[[1, 2, 3]], [[4, 5, 6]]]])

# Try to remove a non-single-dimensional axis
squeezed_array = np.squeeze(array, axis=1)

print(squeezed_array)
print(squeezed_array.shape)

ValueError: cannot select an axis to squeeze out which has size not equal to one

## repeat()

The numpy.repeat() function is used to repeat elements of an array along a specified axis. It allows you to create a new array by repeating the elements of the original array a given number of times, either along a particular axis or for the entire array.

numpy.repeat(a, repeats, axis=None)

Key Points:

Flattening Behavior: If axis is not specified, repeat() flattens the input array and then applies the repetition.

Shape Compatibility: When specifying axis, the length of repeats should match the length of the array along that axis.

#### Example 1: Repeating Elements Without Specifying Axis

In [8]:
# Create an array
array = np.array([1, 2, 3])

# Repeat each element 3 times
repeated_array = np.repeat(array, repeats=3)

repeated_array

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### Example 2: Repeating Elements Along a Specific Axis
Each row of the 2D array is repeated twice along the vertical axis (axis 0)

In [9]:
# Create a 2D array
array = np.array([[1, 2], [3, 4]])

# Repeat elements along axis 0 (rows)
repeated_array_axis0 = np.repeat(array, repeats=2, axis=0)

repeated_array_axis0

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

#### Example 3: Using Different Repeats for Each Element
Here, the element 1 is repeated 1 time, 2 is repeated 2 times, and 3 is repeated 3 times

In [10]:
# Create a 1D array
array = np.array([1, 2, 3])

# Repeat each element a different number of times
repeats = [1, 2, 3]
repeated_array = np.repeat(array, repeats=repeats)

repeated_array

array([1, 2, 2, 3, 3, 3])

#### Example 4: Repeating Along Multiple Axes
In this case, each column of the 2D array is repeated 3 times along the horizontal axis (axis 1).

In [11]:
# Create a 2D array
array = np.array([[1, 2], [3, 4]])

# Repeat elements along axis 1 (columns)
repeated_array_axis1 = np.repeat(array, repeats=3, axis=1)

repeated_array_axis1

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

Use Cases

Data Augmentation: Repeating elements can be useful in data augmentation scenarios, such as creating synthetic data.

Array Manipulation: When preparing data for algorithms or visualizations, you might need to adjust the shape of arrays by repeating elements.

Feature Engineering: Repeating values can be used in feature engineering to generate new features or modify existing ones.

Overall, numpy.repeat() is a versatile function for manipulating array structures and creating new arrays with repeated elements.

## roll()
The numpy.repeat() function is used to repeat elements of an array along a specified axis. It allows you to create a new array by repeating the elements of the original array a given number of times, either along a particular axis or for the entire array.

numpy.repeat(a, repeats, axis=None)

Key Points

Flattening Behavior: If axis is not specified, repeat() flattens the input array and then applies the repetition.

Shape Compatibility: When specifying axis, the length of repeats should match the length of the array along that axis.

#### Example 1: Rolling a 1D Array

In [15]:
arr1 = np.array([1, 2, 3, 3, 4])
arr1

array([1, 2, 3, 3, 4])

In [14]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

#### Example 2: Rolling a 2D Array Along One Axis
In this example, each row is shifted down by 1 position. The last row wraps around to the top

In [22]:
# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])

array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# Roll the array by 1 position along axis 0 (rows)
rolled_array_axis0 = np.roll(array, shift=1, axis=0)

rolled_array_axis0

array([[4, 5, 6],
       [1, 2, 3]])

#### Example 3: Rolling a 2D Array Along Both Axes

Here, the array is shifted down by 1 position along rows and right by 2 positions along columns.

In [18]:
# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Roll the array by 1 position along axis 0 and 2 positions along axis 1
rolled_array_both_axes = np.roll(array, shift=(1, 2), axis=(0, 1))

rolled_array_both_axes

array([[5, 6, 4],
       [2, 3, 1]])

#### Example 4: Rolling a 3D Array

In this case, the array is shifted along the first axis (depth) by 1 position. The last slice wraps around to the first position.

In [23]:
# Create a 3D array
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
# Roll the array by 1 position along axis 0
rolled_array_3d = np.roll(array, shift=1, axis=0)

rolled_array_3d

array([[[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]]])

Use Cases

Circular Buffer: Useful in scenarios where you need to implement circular buffers or rolling windows.

Data Augmentation: In image processing or other tasks, you might use rolling to augment data or adjust input for certain algorithms.

Simulations: Useful in simulations where you need to wrap around values, such as in periodic boundary conditions.

Overall, numpy.roll() is a versatile function for shifting array elements along specified axes, allowing for various applications in data manipulation and processing.

## diag()

In [30]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# Binary Operators.

In [27]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [28]:
arr1

array([[8, 8, 7, 1],
       [8, 5, 9, 1],
       [4, 8, 3, 6]], dtype=int32)

In [29]:
arr2

array([[9, 1, 4, 8],
       [6, 6, 6, 2],
       [5, 6, 1, 2]], dtype=int32)

In [30]:
arr1+arr2

array([[17,  9, 11,  9],
       [14, 11, 15,  3],
       [ 9, 14,  4,  8]], dtype=int32)

In [31]:
arr1*arr2

array([[72,  8, 28,  8],
       [48, 30, 54,  2],
       [20, 48,  3, 12]], dtype=int32)

In [32]:
arr1/arr2

array([[0.88888889, 8.        , 1.75      , 0.125     ],
       [1.33333333, 0.83333333, 1.5       , 0.5       ],
       [0.8       , 1.33333333, 3.        , 3.        ]])

In [33]:
arr1-arr2

array([[-1,  7,  3, -7],
       [ 2, -1,  3, -1],
       [-1,  2,  2,  4]], dtype=int32)

In [34]:
arr1%arr2

array([[8, 0, 3, 1],
       [2, 5, 3, 1],
       [4, 2, 0, 0]], dtype=int32)

In [35]:
arr1 ** arr2

array([[134217728,         8,      2401,         1],
       [   262144,     15625,    531441,         1],
       [     1024,    262144,         3,        36]], dtype=int32)

In [36]:
arr1 & arr2

array([[8, 0, 4, 0],
       [0, 4, 0, 0],
       [4, 0, 1, 2]], dtype=int32)

In [37]:
arr1

array([[8, 8, 7, 1],
       [8, 5, 9, 1],
       [4, 8, 3, 6]], dtype=int32)

In [38]:
arr2

array([[9, 1, 4, 8],
       [6, 6, 6, 2],
       [5, 6, 1, 2]], dtype=int32)

In [39]:
~arr1

array([[ -9,  -9,  -8,  -2],
       [ -9,  -6, -10,  -2],
       [ -5,  -9,  -4,  -7]], dtype=int32)

In [40]:
arr1|arr2

array([[ 9,  9,  7,  9],
       [14,  7, 15,  3],
       [ 5, 14,  3,  6]], dtype=int32)

In [41]:
arr1>arr2

array([[False,  True,  True, False],
       [ True, False,  True, False],
       [False,  True,  True,  True]])

# String Functions.

In [65]:
arr = np.array(['SINCHAN' , "PANDA"])
arr

array(['SINCHAN', 'PANDA'], dtype='<U7')

In [66]:
np.char.upper(arr)

array(['SINCHAN', 'PANDA'], dtype='<U7')

In [85]:
arr = np.array(["Hi user, THis A teST STRing"])
arr

array(['Hi user, THis A teST STRing'], dtype='<U27')

In [86]:
np.char.title(arr)

array(['Hi User, This A Test String'], dtype='<U27')

In [87]:
np.char.capitalize(arr)

array(['Hi user, this a test string'], dtype='<U27')

# Mathematical Functions.

In [88]:
arr1

array([[8, 8, 7, 1],
       [8, 5, 9, 1],
       [4, 8, 3, 6]], dtype=int32)

In [89]:
np.sin(arr1)

array([[ 0.98935825,  0.98935825,  0.6569866 ,  0.84147098],
       [ 0.98935825, -0.95892427,  0.41211849,  0.84147098],
       [-0.7568025 ,  0.98935825,  0.14112001, -0.2794155 ]])

In [90]:
np.cos(arr1)

array([[-0.14550003, -0.14550003,  0.75390225,  0.54030231],
       [-0.14550003,  0.28366219, -0.91113026,  0.54030231],
       [-0.65364362, -0.14550003, -0.9899925 ,  0.96017029]])

In [91]:
np.tan(arr1)

array([[-6.79971146, -6.79971146,  0.87144798,  1.55740772],
       [-6.79971146, -3.38051501, -0.45231566,  1.55740772],
       [ 1.15782128, -6.79971146, -0.14254654, -0.29100619]])

In [92]:
np.tanh(arr1)

array([[0.99999977, 0.99999977, 0.99999834, 0.76159416],
       [0.99999977, 0.9999092 , 0.99999997, 0.76159416],
       [0.9993293 , 0.99999977, 0.99505475, 0.99998771]])

In [93]:
np.log10(arr1)

array([[0.90308999, 0.90308999, 0.84509804, 0.        ],
       [0.90308999, 0.69897   , 0.95424251, 0.        ],
       [0.60205999, 0.90308999, 0.47712125, 0.77815125]])

In [94]:
np.exp(arr1)

array([[2.98095799e+03, 2.98095799e+03, 1.09663316e+03, 2.71828183e+00],
       [2.98095799e+03, 1.48413159e+02, 8.10308393e+03, 2.71828183e+00],
       [5.45981500e+01, 2.98095799e+03, 2.00855369e+01, 4.03428793e+02]])

In [95]:
np.sqrt(arr1)

array([[2.82842712, 2.82842712, 2.64575131, 1.        ],
       [2.82842712, 2.23606798, 3.        , 1.        ],
       [2.        , 2.82842712, 1.73205081, 2.44948974]])

In [103]:
arr1

array([[8, 8, 7, 1],
       [8, 5, 9, 1],
       [4, 8, 3, 6]], dtype=int32)

In [96]:
np.power(arr1,2)

array([[64, 64, 49,  1],
       [64, 25, 81,  1],
       [16, 64,  9, 36]], dtype=int32)

In [97]:
np.mean(arr1)

np.float64(5.666666666666667)

In [98]:
np.median(arr1)

np.float64(6.5)

In [99]:
np.std(arr1)

np.float64(2.718251071716682)

In [100]:
np.var(arr1)

np.float64(7.388888888888889)

In [101]:
np.min(arr1
      )

np.int32(1)

In [102]:
np.max(arr1)

np.int32(9)