# Sort, Search & Counting Functions.

In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [3]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

 The numpy.searchsorted() function is used to find the indices at which elements should be inserted to maintain order in a sorted array. This is particularly useful when you need to efficiently determine the position of elements in a sorted array without having to perform a full search.

In [4]:
np.searchsorted(arr ,34)

np.int64(12)

In [5]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [6]:
np.count_nonzero(arr1)

2

In [7]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

The numpy.where() function is a versatile utility that returns the indices of elements in an array that satisfy a certain condition. It can also be used to select elements from two arrays based on a condition.

numpy.where(condition, [x, y])

condition: An array-like object or condition that specifies where to find the elements.

x (optional): An array or value to select where condition is True.

y (optional): An array or value to select where condition is False

In [8]:
np.where(arr > 6)

(array([5, 8]),)

#### Extract based on condition

In [9]:
np.extract(arr>3 , arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

# Byte Swapping.

In [11]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [12]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

# Copies & Views.

1. Copy
Definition: A copy is a new array that is a separate entity from the original array. Changes to the copy do not affect the original array, and vice versa.


Characteristics:

Independent: Modifications to a copy do not affect the original array and vice versa.

Memory: A copy uses additional memory because it stores a separate, full copy of the data.

Performance: Creating a copy involves additional overhead due to memory allocation and data copying.

2. View
Definition: A view is a new array object that looks at the same data as the original array. Changes to the view will affect the original array, and changes to the original array will reflect in the view.



Characteristics:

Shared Data: Both the view and the original array share the same data buffer. Changes to one affect the other.

Memory: Views are generally more memory-efficient because they do not require copying the data; they merely reference the original data.

Performance: Operations involving views are often faster as they avoid the overhead of copying data.

In [14]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [15]:
a = np.copy(arr)

In [16]:
b = arr.view()

In [17]:
b = arr

In [18]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [19]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
b[0] = 67

In [21]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

# Matrix Library.

Similar like numpy arrays. Instead of array it creats MATRIX directly

In [24]:
import numpy.matlib as nm

In [25]:
nm.zeros(5
        )

matrix([[0., 0., 0., 0., 0.]])

In [26]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Linear Algebra

In [32]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [33]:
arr2 = np.random.randint([[5,3] , [2,5]])


In [35]:
np.dot(arr1, arr2)

array([[ 2,  9],
       [ 2, 17]], dtype=int32)

In [36]:
np.cross(arr1, arr2)

C:\Users\sinch\AppData\Local\Temp\ipykernel_67876\1019698839.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(arr1, arr2)


array([-3,  4], dtype=int32)